### ISSUE TITLE
Proposal for more vivid theme colors

### ISSUE THREAD

**Issue by pista329** [loopsocial/fwego#3]
Buenos días!
Have been replacing some parts of our pwa for fwego components and stumbled upon difference in visual appearance. (see attached screens)

My proposal is for changing theme primary for more vivid colors, more specifically
`linear-gradient(90deg, rgb(255, 59, 87) 0%, rgb(255, 126, 53) 100%)`

Secondly the rounded corners for large do not get 50% radius, seems more like bug.

## Code
```
<Button
      as="a"
      variant="primary"
      size="large"
      minWidth="240"
      maxWidth="100%"
```
## Current "Buy"
<img width="612" alt="Screenshot 2020-05-21 at 02 06 40" src="https://user-images.githubusercontent.com/354922/82509316-d3e07380-9b07-11ea-8c27-7014a3fe641d.png">

## Fwego "Buy"
<img width="612" alt="Screenshot 2020-05-21 at 02 06 56" src="https://user-images.githubusercontent.com/354922/82509311-d216b000-9b07-11ea-8a97-e37baed2030a.png">

**Comment by yufanjiangwastaken** [comment]
![Screen Shot 2020-05-20 at 5 41 52 PM](https://user-images.githubusercontent.com/60454811/82511097-3b270500-9ac1-11ea-9c07-31108869d00a.png)

1. Yes, the original colors are very colorful, but it looks more like an alert color. let's tone it down a bit, if everything is about contrast, we can just use black and white...
2. the reason for using 50% of the height as the radius of a corner is because, in some context, the long button needs change into a circle.

**Comment by pista329** [comment]
Alright then. Thank you guys.

**Comment by bnhansn** [comment]
To follow up about the radius on buttons, it was a css issue in this library. It was set to 18px for all buttons, but that doesn't work for large variants, and it makes that blockish shape in Stefan's screenshot. With css, you can't set the border-radius to 50% of the height and get the pill shape for all variants--the best way I found to accomplish that is `border-radius: 500px`.

Icon buttons also require some different css. I added an `icon` variant to the FW theme, you can check that out here https://loopsocial.github.io/fwego/?path=/story/button--fw-theme
